apiVersion: v1
data:
  dragent.yaml: |
    new_k8s: true
    k8s_cluster_name: foo-bar
    metrics_excess_log: true
    app_checks_enabled: false
    metrics_filter:
    - include: "nginx*"
    - include: "redis*"
    - include: "node*"
    prometheus:
      enabled: true
      histograms: true
      ingest_raw: true
      max_metrics: 3000
      max_metrics_per_process: 3000
      process_filter:
      - include:
          kubernetes.pod.label.app: "nginx-exporter"
          conf:
            port: 9113
            host: 127.0.0.1
      - include:
          kubernetes.pod.annotation.prometheus.io/scrape: true
          conf:
              path: "{kubernetes.pod.annotation.prometheus.io/path}"
              port: "{kubernetes.pod.annotation.prometheus.io/port}"
    snaplen: 512
    tags: role:cluster
kind: ConfigMap
metadata:
    labels:
      app: sysdig-agent
    name: sysdig-agent
    namespace: sysdig-agent
