apiVersion: v1
data:
  dragent.yaml: |
    new_k8s: true
    security:
      enabled: true
    k8s_cluster_name: foo-bar
    metrics_excess_log: true
    metrics_filter:
    - include: apiserver_request_total
    percentiles:
    - 50
    - 95
    - 99
    prometheus:
      enabled: true
      histograms: true
      ingest_raw: true
      max_metrics: 3000
      max_metrics_per_process: 3000
      process_filter:
      - include:
          kubernetes.pod.label.app: "nginx-exporter"
          conf:
            port: 9113
            host: 127.0.0.1
    snaplen: 512
    tags: role:cluster
kind: ConfigMap
metadata:
    labels:
      app: sysdig-agent
    name: sysdig-agent
    namespace: sysdig-agent
